# Process Mapping Workflow Configuration
name: "process-mapping"
description: "Map business processes through guided conversation or document analysis. Extracts current-state workflows, identifies bottlenecks and automation opportunities, and produces structured process maps with Mermaid diagrams. Designed to power the Arise Group website process mapper tool and feed into AI transformation planning."
author: "Arise Group"

# Critical variables load from config_source
config_source: "{project-root}/_bmad/cis/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

# Context can be provided via data attribute when invoking
# Example: data="{path}/transcript.md" provides meeting transcript for extraction

# Module path and component files
installed_path: "{project-root}/_bmad/cis/workflows/process-mapping"
template: "{installed_path}/template.md"
instructions: "{installed_path}/instructions.md"

# Required Data Files
process_categories: "{installed_path}/process-categories.csv"

# Output configuration
default_output_file: "{output_folder}/process-map-{{date}}.md"

standalone: true
